import type { NetworkProfile } from '@eth-netstats/types';

export const KNOWN_NETWORKS: Record<number, NetworkProfile> = {
  1: {
    chainId: 1,
    name: 'Ethereum Mainnet',
    shortName: 'ETH',
    nativeSymbol: 'ETH',
    expectedBlockTime: 12000,
    consensus: 'pos',
    explorerUrl: 'https://etherscan.io',
    maxPropagationMs: 10000,
  },
  137: {
    chainId: 137,
    name: 'Polygon',
    shortName: 'MATIC',
    nativeSymbol: 'MATIC',
    expectedBlockTime: 2000,
    consensus: 'pos',
    explorerUrl: 'https://polygonscan.com',
    maxPropagationMs: 2000,
  },
  56: {
    chainId: 56,
    name: 'BNB Smart Chain',
    shortName: 'BNB',
    nativeSymbol: 'BNB',
    expectedBlockTime: 3000,
    consensus: 'poa',
    explorerUrl: 'https://bscscan.com',
    maxPropagationMs: 3000,
  },
  42161: {
    chainId: 42161,
    name: 'Arbitrum One',
    shortName: 'ARB',
    nativeSymbol: 'ETH',
    expectedBlockTime: 250,
    consensus: 'pos',
    explorerUrl: 'https://arbiscan.io',
    maxPropagationMs: 1000,
  },
  10: {
    chainId: 10,
    name: 'Optimism',
    shortName: 'OP',
    nativeSymbol: 'ETH',
    expectedBlockTime: 2000,
    consensus: 'pos',
    explorerUrl: 'https://optimistic.etherscan.io',
    maxPropagationMs: 2000,
  },
  43114: {
    chainId: 43114,
    name: 'Avalanche C-Chain',
    shortName: 'AVAX',
    nativeSymbol: 'AVAX',
    expectedBlockTime: 2000,
    consensus: 'pos',
    explorerUrl: 'https://snowtrace.io',
    maxPropagationMs: 2000,
  },
  8453: {
    chainId: 8453,
    name: 'Base',
    shortName: 'BASE',
    nativeSymbol: 'ETH',
    expectedBlockTime: 2000,
    consensus: 'pos',
    explorerUrl: 'https://basescan.org',
    maxPropagationMs: 2000,
  },
  100: {
    chainId: 100,
    name: 'Gnosis Chain',
    shortName: 'xDAI',
    nativeSymbol: 'xDAI',
    expectedBlockTime: 5000,
    consensus: 'pos',
    explorerUrl: 'https://gnosisscan.io',
    maxPropagationMs: 5000,
  },
  11155111: {
    chainId: 11155111,
    name: 'Sepolia Testnet',
    shortName: 'SEP',
    nativeSymbol: 'ETH',
    expectedBlockTime: 12000,
    consensus: 'pos',
    explorerUrl: 'https://sepolia.etherscan.io',
    maxPropagationMs: 10000,
  },
  80001: {
    chainId: 80001,
    name: 'Polygon Mumbai',
    shortName: 'MATIC',
    nativeSymbol: 'MATIC',
    expectedBlockTime: 2000,
    consensus: 'pos',
    explorerUrl: 'https://mumbai.polygonscan.com',
    maxPropagationMs: 2000,
  },
};

export const DEFAULT_NETWORK: NetworkProfile = {
  chainId: 0,
  name: 'Custom Network',
  shortName: 'ETH',
  nativeSymbol: 'ETH',
  expectedBlockTime: 12000,
  consensus: 'pos',
  explorerUrl: '',
  maxPropagationMs: 10000,
};
